version: '3.7'

services:

  medihub-mysql-db:
    image: mysql:8.3
    container_name: medihub-mysql-db
    hostname: medihub-mysql-db
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
    restart: always
    volumes:
      - ./databases:/usr/databases
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
  medihub-mysql-workbench:
    image: linuxserver/mysql-workbench:latest
    container_name: medihub-mysql-workbench
    hostname: medihub-mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./databases:/usr/databases
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
